# Inti Pipecat Backend Deployment - Pipecat Branch
# This configuration uses TLS-ALPN challenge for Let's Encrypt (working)
# Updated: September 2025

version: '3.9'

networks:
  unmute-net:
    external: true

volumes:
  traefik-cert:

services:
  # Pipecat Backend Service with Fixed Routing
  backend:
    image: intellipedia/inti-pipecat-backend:dev.10
    environment:
      - GROQ_API_KEY=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
      - INTI_GROQ_LLM_MODEL=openai/gpt-oss-20b
      - INTI_GROQ_STT_MODEL=whisper-large-v3-turbo
      - INTI_GROQ_TTS_VOICE=Celeste-PlayAI
      - INTI_LOG_LEVEL=INFO
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        parallelism: 1
        order: start-first
      labels:
        # Enable Traefik routing
        - "traefik.enable=true"

        # API routing - handles /api/v1/health and other API calls
        - "traefik.http.routers.backend.rule=Host(`inti.intellipedia.ai`) && PathPrefix(`/api`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls.certresolver=le"
        - "traefik.http.routers.backend.middlewares=backend-stripprefix"
        - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
        - "traefik.http.routers.backend.priority=100"
        - "traefik.http.routers.backend.service=pipecat-backend"

        # WebSocket routing - handles /v1/realtime
        - "traefik.http.routers.ws.rule=Host(`inti.intellipedia.ai`) && Path(`/v1/realtime`)"
        - "traefik.http.routers.ws.entrypoints=websecure"
        - "traefik.http.routers.ws.tls.certresolver=le"
        - "traefik.http.routers.ws.priority=110"
        - "traefik.http.routers.ws.service=pipecat-backend"

        - "traefik.http.services.pipecat-backend.loadbalancer.server.port=8000"
    networks:
      - unmute-net

  # Frontend Service (unchanged)
  frontend:
    image: intellipedia/inti-frontend:v15.11.24
    environment:
      - NEXT_PUBLIC_IN_DOCKER=true
      - NEXT_PUBLIC_WS_URL=wss://inti.intellipedia.ai/v1/realtime
      - NEXT_PUBLIC_API_BASE=https://inti.intellipedia.ai/api
      - NEXT_PUBLIC_BACKEND_URL=https://inti.intellipedia.ai/api
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`inti.intellipedia.ai`) && !PathPrefix(`/api`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.http.routers.frontend.tls.certresolver=le"
        - "traefik.http.services.frontend.loadbalancer.server.port=3000"
        - "traefik.http.routers.frontend.priority=50"
    networks:
      - unmute-net

  # Traefik Service with TLS-ALPN Challenge (Working Configuration)
  traefik:
    image: traefik:v3.3.1
    command:
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=steve@intellipedia.ai"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--metrics.prometheus=true"
      - "--log.level=INFO"
      - "--ping=true"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik-cert:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    dns:
      - 1.1.1.1
      - 8.8.8.8
    deploy:
      update_config:
        order: start-first
      placement:
        constraints:
          - node.role == manager
    networks:
      - unmute-net
